In [1]:
image_dimensions = (10,12)
corner_points = [
    (1.5, 1.5),  # (x, y)
    (4.0, 1.5),  # (x, y)
    (1.5, 8.0),  # (x, y)
    (4.0, 8.0)]  # (x, y)


In [2]:
import numpy as np

def calculatePixels(image_dimensions, corner_points):
    max_xy = max(corner_points, key=lambda x: (x[0], x[1]))
    min_xy = min(corner_points, key=lambda x: (x[0], x[1]))
    max_xy
    min_xy
    
    top_left = [min_xy[0], max_xy[1]]
    bottom_left = [min_xy[0], min_xy[1]]
    top_right = [max_xy[0], max_xy[1]]
    bottom_right = [max_xy[0], min_xy[1]]
    
    min_x = min_xy[0]
    max_x = max_xy[0]
    min_y = min_xy[1]
    max_y = max_xy[1]

    x_dim = image_dimensions[0]
    x_dist = max_x - min_x
    x_space = (x_dist) / (x_dim-1)
    x_pts = [float(min_x)]
    for i in range(1, image_dimensions[0]):
        x_pts.append(float(x_pts[i-1]+x_space))

    
    y_dim = image_dimensions[1]
    y_dist = max_y - min_y
    y_space = (y_dist) / (y_dim-1)
    y_pts = [float(min_y)]
    for i in range(1, image_dimensions[1]):
        y_pts.append(float(y_pts[i-1]+y_space))


    solution = np.zeros((image_dimensions[1], image_dimensions[0], 2))
    for i in range(0, image_dimensions[1]):
        for j in range(0, image_dimensions[0]):
            solution[i][j] += [x_pts[j], y_pts[image_dimensions[1]-i-1]]
    return solution




In [3]:
solution = calculatePixels(image_dimensions, corner_points)
np.set_printoptions(precision=4)
print(solution)

[[[1.5    8.    ]
  [1.7778 8.    ]
  [2.0556 8.    ]
  [2.3333 8.    ]
  [2.6111 8.    ]
  [2.8889 8.    ]
  [3.1667 8.    ]
  [3.4444 8.    ]
  [3.7222 8.    ]
  [4.     8.    ]]

 [[1.5    7.4091]
  [1.7778 7.4091]
  [2.0556 7.4091]
  [2.3333 7.4091]
  [2.6111 7.4091]
  [2.8889 7.4091]
  [3.1667 7.4091]
  [3.4444 7.4091]
  [3.7222 7.4091]
  [4.     7.4091]]

 [[1.5    6.8182]
  [1.7778 6.8182]
  [2.0556 6.8182]
  [2.3333 6.8182]
  [2.6111 6.8182]
  [2.8889 6.8182]
  [3.1667 6.8182]
  [3.4444 6.8182]
  [3.7222 6.8182]
  [4.     6.8182]]

 [[1.5    6.2273]
  [1.7778 6.2273]
  [2.0556 6.2273]
  [2.3333 6.2273]
  [2.6111 6.2273]
  [2.8889 6.2273]
  [3.1667 6.2273]
  [3.4444 6.2273]
  [3.7222 6.2273]
  [4.     6.2273]]

 [[1.5    5.6364]
  [1.7778 5.6364]
  [2.0556 5.6364]
  [2.3333 5.6364]
  [2.6111 5.6364]
  [2.8889 5.6364]
  [3.1667 5.6364]
  [3.4444 5.6364]
  [3.7222 5.6364]
  [4.     5.6364]]

 [[1.5    5.0455]
  [1.7778 5.0455]
  [2.0556 5.0455]
  [2.3333 5.0455]
  [2.6111 5.0455]


In [4]:
image_dimensions = (3,3)
corner_points = [
    (1, 1), 
    (3, 1), 
    (1, 3), 
    (3, 3)] 
solution = calculatePixels(image_dimensions, corner_points)
np.set_printoptions(precision=4)
print(solution)

[[[1. 3.]
  [2. 3.]
  [3. 3.]]

 [[1. 2.]
  [2. 2.]
  [3. 2.]]

 [[1. 1.]
  [2. 1.]
  [3. 1.]]]
